[project]
name = "pdm-platform"
version = "0.1.0"
description = "Data platform for industrial machine data (learning project)"
readme = "README.md"
authors = [
    { name = "Philipp Merklinger", email = "32850364+Philipp03@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pdm-platform = "pdm_platform:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.9",
    "sqlfluff>=4.3.0",
]
